// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"
#include "CoreMinimal.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Dash);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Dash_Active);
//UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_ProjectileSpawn_StaffFire);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Stamina_Regen);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Abilities_Changed);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Ranged_Staff);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Melee_Axe);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_ActivateAbility_Dash);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_ActivateAbility_EquipWeapon);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MeleeAttack_AxeSwing);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_MeleeAttack_AxeCombo);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayAbility_ShootProjectile);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_HitScan_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_ContinueCombo_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_HitScan_End);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_ContinueCombo_End);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_ContinueCombo_Input);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_ShootProjectile);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_Damage);

/**
 * 
 */
